/**
 * Export seed thinkers to public/thinkers/*.md with full academic data.
 */
import { SEED_IDS } from '../src/data/thinkers';
import { markdownToData, metadataToThinker } from '../src/utils/markdownIO';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';

// The MD files will be generated by the app's thinkerToMarkdown function.
// We import it dynamically since it uses browser APIs (JSZip).
// Instead, write a full exporter that includes idea details + school theories.

import { IDEA_DETAILS, type IdeaDetail } from '../src/data/ideaDetails';
import { SCHOOL_THEORIES, type TheoryModule } from '../src/data/schoolTheories';
import { IDEA_LABELS } from '../src/data/labels';
import { SCHOOL_LABELS } from '../src/data/schools';

// Minimal equivalent of thinkerToMarkdown (browser-free)
function buildMarkdown(thinker: any): string {
  const school = (SCHOOL_LABELS as any)[thinker.school];
  const ideaDetails: Record<string, IdeaDetail> = { ...IDEA_DETAILS };
  const schoolTheories: Record<string, TheoryModule[]> = { ...SCHOOL_THEORIES };

  // Build core_ideas with details
  const coreIdeasYaml = thinker.coreIdeas
    .map((slug: string) => {
      const label = (IDEA_LABELS as any)[slug];
      const detail = ideaDetails[slug];
      const lines: string[] = [];
      lines.push(`  - slug: "${slug}"`);
      if (label) {
        lines.push(`    label: "${label.zh}"`);
        lines.push(`    label_en: "${label.en}"`);
      }
      if (detail) {
        lines.push(`    definition: "${esc(detail.definition_zh)}"`);
        lines.push(`    origin: "${esc(detail.origin_zh)}"`);
        lines.push(`    evolution: "${esc(detail.evolution_zh)}"`);
        lines.push(`    misconception: "${esc(detail.misconception_zh)}"`);
      }
      return lines.join('\n');
    })
    .join('\n');

  // Build school theories for this thinker's school
  const theories = schoolTheories[thinker.school];
  const schoolTheoriesYaml = theories
    ? theories
        .map((t) =>
          [
            `  - school: "${thinker.school}"`,
            `    slug: "${t.slug}"`,
            `    zh: "${t.zh}"`,
            `    en: "${t.en}"`,
            `    desc_zh: "${esc(t.desc_zh)}"`,
            `    icon: "${t.icon}"`,
          ].join('\n')
        )
        .join('\n')
    : '';

  const frontmatter = [
    '---',
    `id: "${thinker.id}"`,
    `name: "${thinker.name}"`,
    `name_zh: "${thinker.name_zh}"`,
    `born: ${thinker.born}`,
    `died: ${thinker.died}`,
    `latitude: ${thinker.latitude}`,
    `longitude: ${thinker.longitude}`,
    `region: "${thinker.region}"`,
    `school: "${thinker.school}"`,
    `school_label: "${school?.zh || ''}"`,
    `school_label_en: "${school?.en || ''}"`,
    `key_works:`,
    ...thinker.keyWorks.map(
      (w: any) => `  - title: "${w.title}"\n    title_zh: "${w.title_zh}"\n    year: ${w.year}`
    ),
    `influenced_by: [${thinker.influencedBy.map((s: string) => `"${s}"`).join(', ')}]`,
    `influenced: [${thinker.influenced.map((s: string) => `"${s}"`).join(', ')}]`,
    ...(thinker.influenceNotes && Object.keys(thinker.influenceNotes).length > 0
      ? [`influence_notes:`, ...Object.entries(thinker.influenceNotes).map(([k, v]) => `  ${k}: "${esc(v)}"`)]
      : []),
    ...(thinker.influenceEvidence ? [`influence_evidence: "${esc(thinker.influenceEvidence)}"`] : []),
    `core_ideas:`,
    coreIdeasYaml,
    ...(schoolTheoriesYaml ? ['school_theories:', schoolTheoriesYaml] : []),
    ...(thinker.marxConnection ? [`marx_connection: "${esc(thinker.marxConnection)}"`] : []),
    '---',
  ].join('\n');

  return frontmatter + '\n';
}

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

// Load seed thinkers from existing MD files (basic data), then enrich with full export
import { SEED_THINKERS as _unused } from '../src/data/thinkers';

// Actually, load from the existing basic MD files we created earlier
// Re-export with full detail
async function main() {
  mkdirSync('public/thinkers', { recursive: true });

  for (const id of SEED_IDS) {
    try {
      const mdPath = `public/thinkers/${id}.md`;
      const md = readFileSync(mdPath, 'utf-8');
      const parsed = markdownToData(md);
      if (!parsed) { console.warn(`${id}: parse failed`); continue; }
      const thinker = metadataToThinker(parsed.metadata);
      if (!thinker) { console.warn(`${id}: no thinker`); continue; }

      const fullMd = buildMarkdown(thinker);
      writeFileSync(mdPath, fullMd, 'utf-8');
      console.log(`  ✓ ${id}.md`);
    } catch (e) {
      console.warn(`${id}: error -`, e);
    }
  }
  console.log(`\nRe-exported ${SEED_IDS.length} thinkers with full academic data`);
}

main();
